In [3]:
# Importações
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
plt.style.use('seaborn-v0_8')
%matplotlib inline

In [13]:
# Carregando os dados 
df = pd.read_csv(r'C:\Users\laura\OneDrive\Documentos\GitHub\Bootcamp-Finor\data\ibov_retornos_simples.csv', index_col=0, parse_dates=True)
print(df.shape)
df.head()

(1818, 62)

,ABEV3.SA,AXIA3.SA,AXIA6.SA,AZZA3.SA,B3SA3.SA,BBAS3.SA,BBDC3.SA,BBDC4.SA,BBSE3.SA,BEEF3.SA,...,TAEE11.SA,TIMS3.SA,TOTS3.SA,UGPA3.SA,USIM5.SA,VALE3.SA,VBBR3.SA,VIVT3.SA,WEGE3.SA,YDUQ3.SA
Date,,,,,,,,,,,,,,,,,,,,,
2018-01-03,0.002305,-0.012773,-0.016026,0.030195,0.017023,0.012754,0.004254,0.004598,0.000697,-0.007346,...,0.001398,0.000757,0.021227,-0.009874,0.033333,-0.005992,0.0,-0.028985,-0.015188,0.000886
2018-01-04,-0.005520,-0.006469,0.014425,0.031552,0.006438,0.009595,0.018209,0.016407,0.002089,-0.003700,...,-0.015822,-0.004542,-0.006171,0.011678,0.056452,0.004099,0.0,0.010945,-0.009740,-0.004130
2018-01-05,0.003700,-0.009224,-0.025229,-0.033595,0.014499,0.000000,0.000304,0.005665,0.006602,0.011142,...,0.004728,0.008365,0.021569,0.002075,-0.042939,0.015610,0.0,0.002461,0.004099,-0.013626
2018-01-08,-0.001843,0.006572,0.002353,-0.012279,0.004624,0.002376,0.000000,-0.000282,0.005868,-0.033976,...,-0.004706,-0.013574,-0.000640,0.006989,0.010967,0.022227,0.0,0.010555,0.008163,0.003604
2018-01-09,-0.002770,-0.039717,-0.042253,-0.006304,-0.014226,-0.009482,-0.007576,-0.009295,-0.003432,-0.001901,...,-0.018440,0.001529,0.000320,-0.003856,0.010848,-0.003701,0.0,-0.002672,0.016195,-0.017056

In [12]:
import os
os.path.exists(r'C:\Users\laura\OneDrive\Documentos\GitHub\Bootcamp-Finor\data\ibov_retornos_simples.csv')

True

In [19]:
# Estatísticas descritivas básicas 
desc = df.describe().T
desc['skewness'] = df.skew()
desc['kurtosis'] = df.kurtosis()
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', None)
display(desc)

,count,mean,std,min,25%,50%,75%,max,skewness,kurtosis
ABEV3.SA,1818.0,0.000102,0.017863,-0.157818,-0.008785,0.000000,0.008693,0.098712,-0.160972,7.850170
AXIA3.SA,1818.0,0.001045,0.030244,-0.195052,-0.014073,0.000275,0.014966,0.276245,0.566722,9.744129
AXIA6.SA,1818.0,0.001036,0.026968,-0.193256,-0.011855,0.000283,0.013891,0.183105,0.243166,7.866159
AZZA3.SA,1818.0,0.000115,0.026151,-0.166667,-0.014555,-0.000567,0.014369,0.166193,-0.010563,4.742694
B3SA3.SA,1818.0,0.000764,0.024869,-0.161204,-0.013430,0.000000,0.014491,0.192447,0.146989,4.860666
BBAS3.SA,1818.0,0.000856,0.022779,-0.166895,-0.009973,0.000711,0.011487,0.171261,0.037203,10.331878
BBDC3.SA,1818.0,0.000234,0.021494,-0.160127,-0.011030,0.000364,0.010938,0.163276,-0.156936,8.370096
BBDC4.SA,1818.0,0.000263,0.022032,-0.173843,-0.011061,0.000000,0.011300,0.168669,-0.263978,9.495376
BBSE3.SA,1818.0,0.000700,0.016153,-0.095077,-0.008100,0.000803,0.009149,0.107558,-0.130961,4.948245
BEEF3.SA,1818.0,0.000183,0.028089,-0.185748,-0.015097,-0.000999,0.015031,0.181818,-0.132682,5.622750
BPAC11.SA,1818.0,0.001677,0.028373,-0.268633,-0.012615,0.000305,0.015625,0.278941,0.187946,16.145706
BRAP4.SA,1818.0,0.000934,0.022662,-0.166571,-0.011416,0.000412,0.012720,0.182515,0.079626,7.011108
BRKM5.SA,1818.0,-0.000054,0.034192,-0.244731,-0.016581,-0.002466,0.013664,0.317544,1.358750,16.604997
CMIG4.SA,1818.0,0.001251,0.022444,-0.193152,-0.010546,0.000917,0.013125,0.178035,0.011812,8.300997
COGN3.SA,1818.0,-0.000415,0.035234,-0.209486,-0.020408,-0.002981,0.017797,0.194805,0.005987,4.189371
CPFE3.SA,1818.0,0.000734,0.016903,-0.136691,-0.007992,0.000486,0.009579,0.087908,-0.416132,6.998066
CPLE3.SA,1818.0,0.001339,0.020380,-0.143903,-0.009511,0.000581,0.011951,0.196697,0.350189,10.554535
CSAN3.SA,1818.0,0.000217,0.023973,-0.184370,-0.014372,-0.000678,0.014252,0.142592,-0.116037,4.402645
CSMG3.SA,1818.0,0.000838,0.022163,-0.162745,-0.010248,0.000597,0.011536,0.187879,0.118204,9.909651
CSNA3.SA,1818.0,0.000868,0.033220,-0.252925,-0.017504,-0.000794,0.017584,0.208207,0.255173,4.911801
CYRE3.SA,1818.0,0.001020,0.029913,-0.246502,-0.015103,0.000000,0.016675,0.180556,-0.260098,7.388216
DIRR3.SA,1818.0,0.001663,0.027170,-0.182077,-0.013340,0.000817,0.017222,0.115614,-0.230206,3.341877
EGIE3.SA,1818.0,0.000579,0.014385,-0.096285,-0.007340,0.000455,0.008210,0.099224,0.176334,4.643295
ENEV3.SA,1818.0,0.000965,0.021186,-0.193337,-0.010714,0.000404,0.011998,0.135144,-0.446566,8.881154
ENGI11.SA,1818.0,0.000641,0.018900,-0.143272,-0.010119,0.000422,0.011175,0.126999,-0.317384,5.786790
EQTL3.SA,1818.0,0.000800,0.018025,-0.108411,-0.009620,0.000000,0.010844,0.109749,-0.006112,4.360366
FLRY3.SA,1818.0,-0.000028,0.020809,-0.152543,-0.012109,-0.000700,0.011161,0.160969,-0.022048,5.769788
GGBR4.SA,1818.0,0.000761,0.025469,-0.179567,-0.013056,0.000000,0.013686,0.174528,-0.077273,5.227372
GOAU4.SA,1818.0,0.000803,0.024981,-0.212730,-0.012230,0.000000,0.013870,0.206383,-0.277524,8.542389
HAPV3.SA,1818.0,0.000099,0.033300,-0.335616,-0.016667,0.000000,0.015311,0.273196,-0.540889,15.948421
HYPE3.SA,1818.0,0.000154,0.021477,-0.152096,-0.011732,-0.000316,0.011579,0.166181,0.295634,6.282618
ISAE4.SA,1818.0,0.001087,0.018484,-0.092402,-0.006487,0.000404,0.008160,0.448871,9.372385,210.814446
ITSA4.SA,1818.0,0.000618,0.017757,-0.108654,-0.009659,0.000000,0.010374,0.100323,-0.018927,3.720906
ITUB4.SA,1818.0,0.000578,0.019182,-0.179643,-0.010280,0.000260,0.011106,0.110593,-0.316118,6.781971
KLBN11.SA,1818.0,0.000405,0.018073,-0.152228,-0.010064,0.000000,0.010138,0.101184,-0.227065,7.376201
LREN3.SA,1818.0,0.000165,0.027905,-0.211201,-0.015917,-0.000288,0.015227,0.150000,-0.070960,4.497425
MBRF3.SA,1818.0,0.001326,0.030408,-0.238899,-0.015672,0.000000,0.016510,0.252043,0.216411,8.910842
MGLU3.SA,1818.0,0.000353,0.040842,-0.228311,-0.022441,-0.002049,0.020857,0.251429,0.343315,4.302070
MRVE3.SA,1818.0,0.000183,0.031914,-0.201521,-0.017251,-0.000808,0.016815,0.211439,0.039922,4.436647
MULT3.SA,1818.0,0.000431,0.023596,-0.223899,-0.012189,-0.000786,0.012326,0.173044,0.060356,9.966561
PETR3.SA,1818.0,0.001381,0.027735,-0.296758,-0.010651,0.000812,0.014949,0.227554,-1.108065,17.033239
PETR4.SA,1818.0,0.001391,0.027282,-0.296978,-0.010799,0.001037,0.014339,0.222222,-1.068578,16.841358
POMO4.SA,1818.0,0.000971,0.026883,-0.250814,-0.013333,0.000000,0.014652,0.164430,-0.257937,8.332286
PRIO3.SA,1818.0,0.002356,0.037556,-0.365406,-0.016190,0.000361,0.018237,0.322877,0.025414,17.584904
PSSA3.SA,1818.0,0.000868,0.018019,-0.118087,-0.009354,0.000464,0.010987,0.093805,0.131549,2.758620
RADL3.SA,1818.0,0.000312,0.019908,-0.128348,-0.011127,-0.000088,0.011299,0.092879,0.019490,2.586706
RAIL3.SA,1818.0,0.000485,0.022830,-0.165616,-0.012147,0.000000,0.012395,0.221134,0.503945,10.884811
RENT3.SA,1818.0,0.000845,0.027958,-0.234222,-0.014068,-0.000348,0.014717,0.268212,0.276898,11.342417
SANB11.SA,1818.0,0.000442,0.020992,-0.134740,-0.011172,-0.000317,0.011334,0.134101,0.196080,4.886806
SBSP3.SA,1818.0,0.001034,0.023325,-0.178300,-0.011127,0.000630,0.012833,0.174603,0.348737,8.569566
SLCE3.SA,1818.0,0.001120,0.023221,-0.099407,-0.011516,0.000000,0.012154,0.134021,0.323390,2.184320
SUZB3.SA,1818.0,0.000902,0.024200,-0.161309,-0.012114,-0.000386,0.013257,0.217949,0.507977,7.772088
TAEE11.SA,1818.0,0.000765,0.012233,-0.070389,-0.006165,0.000285,0.007295,0.062881,0.062126,2.711244
TIMS3.SA,1818.0,0.000619,0.019047,-0.147771,-0.009996,0.000000,0.010987,0.099631,-0.086063,5.212404
TOTS3.SA,1818.0,0.001084,0.024854,-0.153436,-0.012017,0.000661,0.014466,0.197996,-0.112739,5.695896
UGPA3.SA,1818.0,0.000726,0.039273,-0.213581,-0.014023,-0.000639,0.013295,1.193350,15.438025,469.698985
USIM5.SA,1818.0,0.000313,0.031020,-0.235507,-0.015675,-0.001240,0.015213,0.213931,0.025409,6.247058
VALE3.SA,1818.0,0.000713,0.023179,-0.245592,-0.011266,-0.000082,0.012018,0.213579,-0.011593,15.206642
VBBR3.SA,1818.0,0.000478,0.024891,-0.152931,-0.013020,0.000000,0.012973,0.167184,0.224900,5.343059
VIVT3.SA,1818.0,0.000600,0.016719,-0.123588,-0.008030,0.000093,0.008551,0.123216,0.200677,7.590362
WEGE3.SA,1818.0,0.001154,0.022223,-0.206197,-0.010118,0.000358,0.011918,0.138945,-0.216903,9.103230
YDUQ3.SA,1818.0,0.000268,0.035685,-0.251744,-0.019247,-0.000892,0.018758,0.238044,0.406072,5.480679

In [20]:
desc.to_excel('estatisticas_descritivas.xlsx')
print('Salvo')

Salvo